# hugo server --minify --themesDir ... --baseURL=http://0.0.0.0:1313/theme/hugo-book/


baseURL: https://jingyi3.github.io/mybook
theme: hugo-theme-book
languageCode: en-us
title: Olivia's Notebook
publishDir: docs
