baseURL = "https://jingyi3.github.io/"
theme = "hugo-theme-book"
languageCode = "en-us"
title = "Olivia's Notebook"
publishDir = "docs"

defaultContentLanguage = "en"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true


